# Yazi theme configuration
# Based on Catppuccin Macchiato theme for consistency

[flavor]
use = "catppuccin-macchiato"

[manager]
cwd = { fg = "blue" }

# Hovered
hovered         = { fg = "black", bg = "yellow" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "yellow", italic = true }
find_position = { fg = "magenta", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "yellow",  bg = "yellow" }
marker_copied   = { fg = "green",   bg = "green" }
marker_cut      = { fg = "red",     bg = "red" }

# Tab
tab_active   = { fg = "black", bg = "blue" }
tab_inactive = { fg = "white", bg = "surface0" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "surface0" }

# Highlighting
syntect_theme = "~/.config/yazi/Catppuccin-macchiato.tmTheme"

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "surface0", bg = "surface0" }

# Mode
mode_normal = { fg = "black", bg = "blue", bold = true }
mode_select = { fg = "black", bg = "green", bold = true }
mode_unset  = { fg = "black", bg = "red", bold = true }

# Progress
progress_label  = { fg = "white", bold = true }
progress_normal = { fg = "blue", bg = "surface0" }
progress_error  = { fg = "red", bg = "surface0" }

# Permissions
permissions_t = { fg = "green" }
permissions_r = { fg = "yellow" }
permissions_w = { fg = "red" }
permissions_x = { fg = "cyan" }
permissions_s = { fg = "magenta" }

[input]
border   = { fg = "blue" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "blue" }
active   = { fg = "magenta" }
inactive = {}

[tasks]
border  = { fg = "blue" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "surface0" }
cand            = { fg = "cyan" }
rest            = { fg = "overlay2" }
desc            = { fg = "magenta" }
separator       = "  "
separator_style = { fg = "surface0" }

[help]
on      = { fg = "magenta" }
exec    = { fg = "cyan" }
desc    = { fg = "overlay2" }
hovered = { bg = "surface0", bold = true }
footer  = { fg = "white", bg = "surface0" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "cyan" },

	# Videos
	{ mime = "video/*", fg = "yellow" },
	{ mime = "audio/*", fg = "yellow" },

	# Archives
	{ mime = "application/zip",             fg = "magenta" },
	{ mime = "application/gzip",            fg = "magenta" },
	{ mime = "application/x-tar",           fg = "magenta" },
	{ mime = "application/x-bzip2",         fg = "magenta" },
	{ mime = "application/x-7z-compressed", fg = "magenta" },
	{ mime = "application/x-rar",           fg = "magenta" },
	{ mime = "application/xz",              fg = "magenta" },

	# Documents
	{ mime = "application/doc",   fg = "green" },
	{ mime = "application/pdf",   fg = "green" },
	{ mime = "application/rtf",   fg = "green" },
	{ mime = "application/vnd.*", fg = "green" },

	# Empty files
	{ mime = "inode/x-empty", fg = "red" },

	# Special files
	{ name = "*", is = "orphan", bg = "red" },
	{ name = "*", is = "exec"  , fg = "green" },

	# Fallback
	{ name = "*/", fg = "blue" }
]
