# Yazi configuration
# Based on best practices from dotfiles-docs.vercel.app

[manager]
ratio = [1, 4, 3]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_hidden = false
show_symlink = true
scrolloff = 5
mouse_events = ["click", "scroll"]
title_format = "Yazi: {cwd}"

[preview]
tab_size = 2
max_width = 600
max_height = 900
cache_dir = ""
image_filter = "triangle"
image_quality = 75
sixel_fraction = 15
ueberzug_scale = 1
ueberzug_offset = [0, 0]

[opener]
edit = [
	{ run = 'nvim "$@"', desc = "Edit with Neovim", block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$1"', desc = "Open", for = "linux" },
]
reveal = [
	{ run = 'xdg-open "$(dirname "$1")"', desc = "Reveal", for = "linux" },
]
extract = [
	{ run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
]
play = [
	{ run = 'mpv "$@"', desc = "Play with mpv", for = "unix" },
]

[open]
rules = [
	{ name = "*/", use = [ "edit", "open", "reveal" ] },

	{ mime = "text/*", use = [ "edit", "reveal" ] },
	{ mime = "image/*", use = [ "open", "reveal" ] },
	{ mime = "video/*", use = [ "play", "reveal" ] },
	{ mime = "audio/*", use = [ "play", "reveal" ] },
	{ mime = "inode/x-empty", use = [ "edit", "reveal" ] },

	{ mime = "application/json", use = [ "edit", "reveal" ] },
	{ mime = "*/javascript", use = [ "edit", "reveal" ] },

	{ mime = "application/zip", use = [ "extract", "reveal" ] },
	{ mime = "application/gzip", use = [ "extract", "reveal" ] },
	{ mime = "application/x-tar", use = [ "extract", "reveal" ] },
	{ mime = "application/x-bzip2", use = [ "extract", "reveal" ] },
	{ mime = "application/x-7z-compressed", use = [ "extract", "reveal" ] },
	{ mime = "application/x-rar", use = [ "extract", "reveal" ] },
	{ mime = "application/xz", use = [ "extract", "reveal" ] },
]

[tasks]
micro_workers = 10
macro_workers = 25
bizarre_retry = 5
image_alloc = 536870912  # 512MB
image_bound = [0, 0]
suppress_preload = false

[plugin]
prepend_preloaders = [
	{ name = "*", cond = "!mime", run = "mime", multi = true, prio = "high" },
]
preloaders = [
	# Archive previews
	{ mime = "application/zip", run = "archive" },
	{ mime = "application/*tar", run = "archive" },
	{ mime = "application/x-rar", run = "archive" },
	{ mime = "application/x-7z-compressed", run = "archive" },

	# Image previews
	{ mime = "image/vnd.djvu", run = "noop" },
	{ mime = "image/*", run = "image" },

	# Video previews
	{ mime = "video/*", run = "video" },

	# PDF previews
	{ mime = "application/pdf", run = "pdf" },

	# Font previews
	{ mime = "font/*", run = "font" },
	{ mime = "application/vnd.ms-opentype", run = "font" },

	# Code previews
	{ mime = "text/*", run = "code" },
	{ mime = "*/xml", run = "code" },
	{ mime = "*/javascript", run = "code" },
	{ mime = "*/x-wine-extension-ini", run = "code" },

	# JSON previews
	{ mime = "application/json", run = "json" },

	# Empty files
	{ mime = "inode/x-empty", run = "empty" },
]

append_preloaders = []

prepend_previewers = [
	{ name = "*", cond = "!mime", run = "mime", multi = true, prio = "high" },
]
previewers = [
	# Archive previews
	{ mime = "application/zip", run = "archive" },
	{ mime = "application/*tar", run = "archive" },
	{ mime = "application/x-rar", run = "archive" },
	{ mime = "application/x-7z-compressed", run = "archive" },

	# Fallback
	{ name = "*", run = "file" },
]
append_previewers = []

[input]
cursor_blink = false

# Find more at https://yazi-rs.github.io/docs/configuration/yazi
