# Yazi keymap configuration
# Based on best practices from dotfiles-docs.vercel.app

[manager]

keymap = [
	{ on = [ "<Esc>" ], run = "escape",             desc = "Exit visual mode, clear selected, or cancel search" },
	{ on = [ "<C-[>" ], run = "escape",             desc = "Exit visual mode, clear selected, or cancel search" },
	{ on = [ "q" ],     run = "quit",               desc = "Exit the process" },
	{ on = [ "Q" ],     run = "quit --no-cwd-file", desc = "Exit the process without writing cwd-file" },
	{ on = [ "<C-c>" ], run = "close",              desc = "Close the current tab, or quit if it is last tab" },
	{ on = [ "<C-z>" ], run = "suspend",            desc = "Suspend the process" },

	# Hopping
	{ on = [ "k" ], run = "arrow -1", desc = "Move cursor up" },
	{ on = [ "j" ], run = "arrow 1",  desc = "Move cursor down" },

	{ on = [ "<Up>" ],   run = "arrow -1", desc = "Move cursor up" },
	{ on = [ "<Down>" ], run = "arrow 1",  desc = "Move cursor down" },

	{ on = [ "<C-u>" ], run = "arrow -50%", desc = "Move cursor up half page" },
	{ on = [ "<C-d>" ], run = "arrow 50%",  desc = "Move cursor down half page" },

	{ on = [ "<C-b>" ], run = "arrow -100%", desc = "Move cursor up one page" },
	{ on = [ "<C-f>" ], run = "arrow 100%",  desc = "Move cursor down one page" },

	{ on = [ "<S-Up>" ],   run = "arrow -5", desc = "Move cursor up 5 lines" },
	{ on = [ "<S-Down>" ], run = "arrow 5",  desc = "Move cursor down 5 lines" },

	{ on = [ "<A-k>" ], run = "arrow -5", desc = "Move cursor up 5 lines" },
	{ on = [ "<A-j>" ], run = "arrow 5",  desc = "Move cursor down 5 lines" },

	# Navigation
	{ on = [ "h" ], run = "leave", desc = "Go back to the parent directory" },
	{ on = [ "l" ], run = "enter", desc = "Enter the child directory" },

	{ on = [ "<Left>" ],  run = "leave", desc = "Go back to the parent directory" },
	{ on = [ "<Right>" ], run = "enter", desc = "Enter the child directory" },

	{ on = [ "H" ], run = "back",    desc = "Go back to the previous directory" },
	{ on = [ "L" ], run = "forward", desc = "Go forward to the next directory" },

	# Seeking
	{ on = [ "K" ], run = "seek -5", desc = "Seek up 5 units in the preview" },
	{ on = [ "J" ], run = "seek 5",  desc = "Seek down 5 units in the preview" },

	# Selection
	{ on = [ "<Space>" ], run = "toggle", desc = "Toggle the current selection state" },
	{ on = [ "v" ],       run = "visual_mode", desc = "Enter visual mode (selection mode)" },
	{ on = [ "V" ],       run = "visual_mode --unset", desc = "Enter visual mode (unset mode)" },
	{ on = [ "<C-a>" ],   run = "select_all --state=true", desc = "Select all files" },
	{ on = [ "<C-r>" ],   run = "select_all --state=false", desc = "Inverse selection of all files" },

	# Operation
	{ on = [ "o" ],         run = "open", desc = "Open the selected files" },
	{ on = [ "<Enter>" ],   run = "open", desc = "Open the selected files" },
	{ on = [ "<C-Enter>" ], run = "open --interactive", desc = "Open the selected files interactively" },
	{ on = [ "y" ],         run = "yank", desc = "Copy the selected files" },
	{ on = [ "x" ],         run = "yank --cut", desc = "Cut the selected files" },
	{ on = [ "p" ],         run = "paste", desc = "Paste the files" },
	{ on = [ "P" ],         run = "paste --force", desc = "Paste the files (overwrite if the destination exists)" },
	{ on = [ "-" ],         run = "link", desc = "Symlink the absolute path of files" },
	{ on = [ "_" ],         run = "link --relative", desc = "Symlink the relative path of files" },
	{ on = [ "d" ],         run = "remove", desc = "Move the files to the trash" },
	{ on = [ "D" ],         run = "remove --permanently", desc = "Permanently delete the files" },
	{ on = [ "a" ],         run = "create", desc = "Create a file or directory (ends with / for directories)" },
	{ on = [ "r" ],         run = "rename --cursor=before_ext", desc = "Rename a file or directory" },
	{ on = [ ";" ],         run = "shell", desc = "Run a shell command" },
	{ on = [ ":" ],         run = "shell --block", desc = "Run a shell command (block the UI until the command finishes)" },
	{ on = [ "." ],         run = "hidden toggle", desc = "Toggle the visibility of hidden files" },
	{ on = [ "s" ],         run = "search fd", desc = "Search files by name using fd" },
	{ on = [ "S" ],         run = "search rg", desc = "Search files by content using ripgrep" },
	{ on = [ "<C-s>" ],     run = "search none", desc = "Cancel the ongoing search" },
	{ on = [ "z" ],         run = "jump zoxide", desc = "Jump to a directory using zoxide" },
	{ on = [ "Z" ],         run = "jump fzf", desc = "Jump to a directory, or reveal a file using fzf" },

	# Linemode
	{ on = [ "m", "s" ], run = "linemode size",        desc = "Set linemode to size" },
	{ on = [ "m", "p" ], run = "linemode permissions", desc = "Set linemode to permissions" },
	{ on = [ "m", "c" ], run = "linemode ctime",       desc = "Set linemode to ctime" },
	{ on = [ "m", "m" ], run = "linemode mtime",       desc = "Set linemode to mtime" },
	{ on = [ "m", "o" ], run = "linemode owner",       desc = "Set linemode to owner" },
	{ on = [ "m", "n" ], run = "linemode none",        desc = "Set linemode to none" },

	# Copy
	{ on = [ "c", "c" ], run = "copy path",             desc = "Copy the absolute path" },
	{ on = [ "c", "d" ], run = "copy dirname",          desc = "Copy the path of the parent directory" },
	{ on = [ "c", "f" ], run = "copy filename",         desc = "Copy the name of the file" },
	{ on = [ "c", "n" ], run = "copy name_without_ext", desc = "Copy the name of the file without the extension" },

	# Filter
	{ on = [ "f" ], run = "filter --smart", desc = "Filter the files" },

	# Find
	{ on = [ "/" ], run = "find --smart",            desc = "Find next file" },
	{ on = [ "?" ], run = "find --previous --smart", desc = "Find previous file" },
	{ on = [ "n" ], run = "find_arrow",              desc = "Go to next found file" },
	{ on = [ "N" ], run = "find_arrow --previous",   desc = "Go to previous found file" },

	# Sorting
	{ on = [ ",", "m" ], run = "sort modified --dir_first",               desc = "Sort by modified time" },
	{ on = [ ",", "M" ], run = "sort modified --reverse --dir_first",     desc = "Sort by modified time (reverse)" },
	{ on = [ ",", "c" ], run = "sort created --dir_first",                desc = "Sort by created time" },
	{ on = [ ",", "C" ], run = "sort created --reverse --dir_first",      desc = "Sort by created time (reverse)" },
	{ on = [ ",", "e" ], run = "sort extension --dir_first",              desc = "Sort by extension" },
	{ on = [ ",", "E" ], run = "sort extension --reverse --dir_first",    desc = "Sort by extension (reverse)" },
	{ on = [ ",", "a" ], run = "sort alphabetical --dir_first",           desc = "Sort alphabetically" },
	{ on = [ ",", "A" ], run = "sort alphabetical --reverse --dir_first", desc = "Sort alphabetically (reverse)" },
	{ on = [ ",", "n" ], run = "sort natural --dir_first",                desc = "Sort naturally" },
	{ on = [ ",", "N" ], run = "sort natural --reverse --dir_first",      desc = "Sort naturally (reverse)" },
	{ on = [ ",", "s" ], run = "sort size --dir_first",                   desc = "Sort by size" },
	{ on = [ ",", "S" ], run = "sort size --reverse --dir_first",         desc = "Sort by size (reverse)" },
	{ on = [ ",", "r" ], run = "sort random --dir_first",                 desc = "Sort randomly" },

	# Tabs
	{ on = [ "t" ], run = "tab_create --current", desc = "Create a new tab using the current path" },

	{ on = [ "1" ], run = "tab_switch 0", desc = "Switch to the first tab" },
	{ on = [ "2" ], run = "tab_switch 1", desc = "Switch to the second tab" },
	{ on = [ "3" ], run = "tab_switch 2", desc = "Switch to the third tab" },
	{ on = [ "4" ], run = "tab_switch 3", desc = "Switch to the fourth tab" },
	{ on = [ "5" ], run = "tab_switch 4", desc = "Switch to the fifth tab" },
	{ on = [ "6" ], run = "tab_switch 5", desc = "Switch to the sixth tab" },
	{ on = [ "7" ], run = "tab_switch 6", desc = "Switch to the seventh tab" },
	{ on = [ "8" ], run = "tab_switch 7", desc = "Switch to the eighth tab" },
	{ on = [ "9" ], run = "tab_switch 8", desc = "Switch to the ninth tab" },

	{ on = [ "[" ], run = "tab_switch -1 --relative", desc = "Switch to the previous tab" },
	{ on = [ "]" ], run = "tab_switch 1 --relative",  desc = "Switch to the next tab" },

	{ on = [ "{" ], run = "tab_swap -1", desc = "Swap the current tab with the previous tab" },
	{ on = [ "}" ], run = "tab_swap 1",  desc = "Swap the current tab with the next tab" },

	# Tasks
	{ on = [ "w" ], run = "tasks_show", desc = "Show the tasks manager" },

	# Goto
	{ on = [ "g", "h" ],       run = "cd ~",             desc = "Go to the home directory" },
	{ on = [ "g", "c" ],       run = "cd ~/.config",     desc = "Go to the config directory" },
	{ on = [ "g", "d" ],       run = "cd ~/Downloads",   desc = "Go to the downloads directory" },
	{ on = [ "g", "t" ],       run = "cd /tmp",          desc = "Go to the temporary directory" },
	{ on = [ "g", "D" ],       run = "cd ~/Development", desc = "Go to the development directory" },
	{ on = [ "g", "<Space>" ], run = "cd --interactive", desc = "Go to a directory interactively" },

	# Help
	{ on = [ "~" ], run = "help", desc = "Open help" },
]

[tasks]

keymap = [
	{ on = [ "<Esc>" ], run = "close", desc = "Hide the task manager" },
	{ on = [ "<C-[>" ], run = "close", desc = "Hide the task manager" },
	{ on = [ "<C-c>" ], run = "close", desc = "Hide the task manager" },
	{ on = [ "w" ],     run = "close", desc = "Hide the task manager" },

	{ on = [ "k" ], run = "arrow -1", desc = "Move cursor up" },
	{ on = [ "j" ], run = "arrow 1",  desc = "Move cursor down" },

	{ on = [ "<Up>" ],   run = "arrow -1", desc = "Move cursor up" },
	{ on = [ "<Down>" ], run = "arrow 1",  desc = "Move cursor down" },

	{ on = [ "<Enter>" ], run = "inspect", desc = "Inspect the task" },
	{ on = [ "x" ],       run = "cancel",  desc = "Cancel the task" },

	{ on = [ "~" ], run = "help", desc = "Open help" }
]

[select]

keymap = [
	{ on = [ "<C-c>" ],   run = "close",          desc = "Cancel selection" },
	{ on = [ "<Esc>" ],   run = "close",          desc = "Cancel selection" },
	{ on = [ "<C-[>" ],   run = "close",          desc = "Cancel selection" },
	{ on = [ "<Enter>" ], run = "close --submit", desc = "Submit the selection" },

	{ on = [ "k" ], run = "arrow -1", desc = "Move cursor up" },
	{ on = [ "j" ], run = "arrow 1",  desc = "Move cursor down" },

	{ on = [ "<Up>" ],   run = "arrow -1", desc = "Move cursor up" },
	{ on = [ "<Down>" ], run = "arrow 1",  desc = "Move cursor down" },

	{ on = [ "~" ], run = "help", desc = "Open help" }
]

[input]

keymap = [
	{ on = [ "<C-c>" ],   run = "close",          desc = "Cancel input" },
	{ on = [ "<Esc>" ],   run = "close",          desc = "Cancel input" },
	{ on = [ "<C-[>" ],   run = "close",          desc = "Cancel input" },
	{ on = [ "<Enter>" ], run = "close --submit", desc = "Submit the input" },
	{ on = [ "<C-u>" ],   run = "kill_bol",       desc = "Kill backwards to the BOL" },
	{ on = [ "<C-k>" ],   run = "kill_eol",       desc = "Kill forwards to the EOL" },
	{ on = [ "<C-h>" ],   run = "backspace",      desc = "Delete the character before the cursor" },
	{ on = [ "<C-d>" ],   run = "delete",         desc = "Delete the character under the cursor" },

	{ on = [ "<C-a>" ], run = "move_bol", desc = "Move cursor to the beginning of the line" },
	{ on = [ "<C-e>" ], run = "move_eol", desc = "Move cursor to the end of the line" },
	{ on = [ "<C-b>" ], run = "move -1",  desc = "Move cursor one character left" },
	{ on = [ "<C-f>" ], run = "move 1",   desc = "Move cursor one character right" },

	{ on = [ "<A-f>" ], run = "forward",      desc = "Move cursor one word right" },
	{ on = [ "<A-b>" ], run = "backward",     desc = "Move cursor one word left" },
	{ on = [ "<A-d>" ], run = "kill_word",    desc = "Kill the next word" },
	{ on = [ "<A-Backspace>" ], run = "kill_word_backward", desc = "Kill previous word" },

	{ on = [ "~" ], run = "help", desc = "Open help" }
]

[help]

keymap = [
	{ on = [ "<Esc>" ], run = "escape", desc = "Clear the filter, or hide the help" },
	{ on = [ "<C-[>" ], run = "escape", desc = "Clear the filter, or hide the help" },
	{ on = [ "q" ],     run = "close",  desc = "Exit the process" },
	{ on = [ "<C-c>" ], run = "close",  desc = "Hide the help" },

	# Navigation
	{ on = [ "k" ], run = "arrow -1", desc = "Move cursor up" },
	{ on = [ "j" ], run = "arrow 1",  desc = "Move cursor down" },

	{ on = [ "<Up>" ],   run = "arrow -1", desc = "Move cursor up" },
	{ on = [ "<Down>" ], run = "arrow 1",  desc = "Move cursor down" },

	# Filtering
	{ on = [ "f" ], run = "filter", desc = "Apply a filter for the help items" },
]
